# Generated by Django 5.1.1 on 2024-09-17 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Franquia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('descricao', models.CharField(max_length=200)),
                ('endereco', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Pratos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('descricao', models.CharField(max_length=200)),
                ('categoria', models.CharField(choices=[('M', 'Massas'), ('A', 'Asiática'), ('C', 'Carnes'), ('V', 'Vegetariano'), ('F', 'Frutos do Mar')], default='V', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('descricao', models.CharField(max_length=200)),
                ('franquia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurantesAPI.franquia')),
            ],
        ),
    ]
