# Generated by Django 5.1.1 on 2024-09-19 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantesAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurante',
            name='pratos',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='restaurantesAPI.pratos'),
        ),
    ]
