# Generated by Django 5.1.1 on 2024-09-19 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantesAPI', '0005_alter_restaurante_pratos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurante',
            name='pratos',
        ),
    ]
