# Generated by Django 5.1.1 on 2024-09-19 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantesAPI', '0006_remove_restaurante_pratos'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurante',
            name='pratos',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='restaurantesAPI.pratos'),
            preserve_default=False,
        ),
    ]
